Translator = {
        "Abandon" : "त्यागना",
        "Ability" : "क्षमता",
        "Accept" : "स्वीकार",
        "Accident" : "दुर्घटना",
        "Account" : "खाता",
        "Achieve" : "प्राप्त करना",
        "Action" : "कार्य",
        "Activity" : "गतिविधि",
        "Add" : "जोड़ना",
        "Address" : "पता",
        "Advice" : "सलाह",
        "Afraid" : "डरना",
        "Age" : "आयु",
        "Agree" : "सहमत होना",
        "Air" : "हवा",
        "Allow" : "अनुमति देना",
        "Always" : "हमेशा",
        "Amount" : "मात्रा",
        "Animal" : "जानवर",
        "Answer" : "उत्तर",
        "Appear" : "प्रकट होना",
        "Apply" : "आवेदन करना",
        "Area" : "क्षेत्र",
        "Argue" : "बहस करना",
        "Arm" : "बांह",
        "Arrive" : "पहुंचना",
        "Ask" : "पूछना",
        "Attack" : "हमला",
        "Attempt" : "प्रयास",
        "Attend" : "उपस्थित होना",
        "Avoid" : "बचना",
        "Baby" : "बच्चा",
        "Back" : "पीछे",
        "Bad" : "बुरा",
        "Bag" : "बैग",
        "Ball" : "गेंद",
        "Bank" : "बैंक",
        "Base" : "आधार",
        "Beautiful" : "सुंदर",
        "Become" : "बनना",
        "Begin" : "शुरू करना",
        "Believe" : "विश्वास करना",
        "Benefit" : "लाभ",
        "Best" : "सर्वश्रेष्ठ",
        "Better" : "बेहतर",
        "Big" : "बड़ा",
        "Bill" : "बिल",
        "Bird" : "पक्षी",
        "Birth" : "जन्म",
        "Black" : "काला",
        "Blood" : "रक्त",
        "Blue" : "नीला",
        "Body" : "शरीर",
        "Book" : "पुस्तक",
        "Born" : "जन्म लेना",
        "Both" : "दोनों",
        "Box" : "डिब्बा",
        "Boy" : "लड़का",
        "Break" : "तोड़ना",
        "Bring" : "लाना",
        "Build" : "बनाना",
        "Business" : "व्यवसाय",
        "Buy" : "खरीदना",
        "Call" : "बुलाना",
        "Camera" : "कैमरा",
        "Care" : "देखभाल",
        "Carry" : "ले जाना",
        "Catch" : "पकड़ना",
        "Cause" : "कारण",
        "Center" : "केंद्र",
        "Change" : "बदलना",
        "Check" : "जांच करना",
        "Child" : "बच्चा",
        "Choose" : "चुनना",
        "City" : "शहर",
        "Class" : "कक्षा",
        "Clean" : "साफ",
        "Clear" : "स्पष्ट",
        "Close" : "बंद करना",
        "Cold" : "ठंडा",
        "College" : "महाविद्यालय",
        "Come" : "आना",
        "Common" : "सामान्य",
        "Company" : "कंपनी",
        "Complete" : "पूरा करना",
        "Computer" : "कंप्यूटर",
        "Condition" : "स्थिति",
        "Consider" : "विचार करना",
        "Continue" : "जारी रखना",
        "Control" : "नियंत्रण",
        "Cook" : "पकाना",
        "Correct" : "सही",
        "Cost" : "लागत",
        "Country" : "देश",
        "Course" : "पाठ्यक्रम",
        "Create" : "बनाना",
        "Culture" : "संस्कृति",
        "Current" : "वर्तमान",
        "Customer" : "ग्राहक",
        "Cut" : "काटना"
}
word = input("Enter a word to translate: \t")
print(Translator[word])